package net.ncue.mart.model;

public enum Msg {
	FAIL,
	SUCCESS,
	LOGOUT,
	LOGIN,
	NOT_EXIST_NAME, 
	NOT_EXIST_EMAIL, 
	NOT_EXIST_PASSWORD, 
	NOT_EXIST_PHONE, 
	NOT_EXIST_SEX, 
	NOT_EXIST_BIRTHYEAR, 
	NOT_EXIST_BIRTHMONTH, 
	NOT_EXIST_BIRTHDATE, 
	WRONG_PASSWORD,
	SAME_EMAIL,
	SUCCESS_CHANGE_PASSWORD
}
